name: "get-net-sdk-project-versions-action"
description: "get .NET SDK project version from csproj/vbproj. "
author: "naminodarie"
inputs:
  proj-path:
    required: true
    description: "csproj/vbproj path"
outputs:
  version:
    description: "version"
  version-prefix:
    description: "version prefix"
  version-suffix:
    description: "version suffix"
  package-version:
    description: "nuget package version"
  assembly-version:
    description: "assembly version"
  file-version:
    description: "file version"
  informational-version:
    description: "informational version"
runs:
  using: "node12"
  main: "dist/index.js"
